### ISSUE TITLE
"There is no current event loop"

### ISSUE THREAD

**Issue by TheFestiveGoose** [hamiltlr/discord-smtp-relay#4]
First, this is EXACTLY what I've been looking for.

I'm getting an error when launching the script. It outputs the following

_DeprecationWarning: There is no current event loop
  loop = asyncio.get_event_loop()_

I'm running Python 3.10, not using docker.

**Comment by hamiltlr** [comment]
Hello!

I believe that error is just a warning, and the script should still work. But I'll look into getting rid of the warning.

**Comment by hamiltlr** [comment]
This should be fixed now, so I'm going to close the issue. Let me know if you hit any more problems!
